services:
  backend:
    image: image_vision_ai
    pull_policy: never
    container_name: image_vision_ai_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  postgres:
    image: postgres:alpine3.20
    restart: always
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      ./src/image_vision_ai/postgres/.env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin_container
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      ./src/image_vision_ai/pgadmin/.env
    ports:
      - 80:80
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
